{% set name = "runpynb" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 46aa74433456eb14fb5738bd259024e979e4d9472d9c1984eb66d8f085676962

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - nbconvert
    - nbformat
    - python >=3.6

test:
  imports:
    - runpynb

about:
  home: https://github.com/lsys/runPyNB
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Run (and time) Jupyter Notebooks for command-line and makefile
  doc_url: http://runpynb.rtfd.io/
  dev_url: https://github.com/lsys/runPyNB

extra:
  recipe-maintainers:
    - lsys
